export enum OrganisationConfigurationActionTypes {
  RESET_FORM = "RESET_FORM",
  FORM_TOUCHED = "FORM_TOUCHED",
  VALIDE_ADDRESS_FORM = "VALIDE_ADDRESS_FORM",
  VALIDE_CONTACT_DETAILS_FORM = "VALIDE_CONTACT_DETAILS_FORM",
  VALIDE_ORGANIZATIONAL_DETAILS_FORM = "VALIDE_ORGANIZATIONAL_DETAILS_FORM",
  CLICK_SAVE_BUTTON = "CLICK_SAVE_BUTTON",
  SAVE_ADDRESS_FORM = "SAVE_ADDRESS_FORM",
  SAVE_CONTACT_DETAILS_FORM = "SAVE_CONTACT_DETAILS_FORM",
  SAVE_ORGANIZATION_DETAILS_FORM = "SAVE_ORGANIZATION_DETAILS_FORM",
}
